// <auto-generated />
namespace StudentRegistration.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changestostudent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changestostudent));
        
        string IMigrationMetadata.Id
        {
            get { return "202102252159013_changes to student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
